/**
 * User-agent crawler detection, for deciding whether a request deserves paid
 * personalization.
 *
 * This is NOT access control. Crawlers are welcome on the storefront and must
 * keep getting fully rendered pages, so nothing here blocks a request — that is
 * what `botid.server.ts` is for, and it returns a 403, which would be exactly
 * the wrong answer on a PDP we want indexed.
 *
 * WHY IT EXISTS. The PDP's contextual Emma aside is generated by Haiku when the
 * visitor has something to personalize against (a cart, browse history, or an
 * account). The browse history comes from a cookie the PDP itself sets, so a
 * crawler that retains cookies accumulates one and starts looking personalized:
 * on the night of 2026-07-21 something walked 2,709 distinct products and spent
 * 3,566 Haiku calls doing it, and `emma-aside` became roughly 47% of all
 * metered API spend (~$40/month) against a site seeing about 26 human sessions
 * a week.
 *
 * Nothing is lost by skipping it. The server-rendered HTML already contains
 * `emmaAsideStatic` (the approved admin aside, or the per-product template
 * fallback), which is the copy crawlers should be indexing anyway: it is stable
 * across renders, where a per-visitor generation is not.
 */

/**
 * Substrings that identify automated clients, lowercased. Deliberately broad on
 * the generic tokens (`bot`, `crawler`, `spider`) because a false positive
 * costs a personalized sentence while a false negative costs money on every
 * page of a catalog walk.
 */
const CRAWLER_TOKENS: readonly string[] = [
  'bot', 'crawler', 'spider', 'crawling',
  'slurp', 'archiver', 'scraper', 'fetcher', 'monitor',
  // Named crawlers whose UA does not always carry a generic token.
  'googlebot', 'bingbot', 'yandex', 'duckduckbot', 'baiduspider',
  'applebot', 'facebookexternalhit', 'ia_archiver', 'semrush', 'ahrefs',
  'mj12', 'dotbot', 'petalbot', 'bytespider', 'gptbot', 'claudebot',
  'ccbot', 'perplexitybot', 'chatgpt-user', 'oai-searchbot', 'anthropic-ai',
  // Headless and scripted clients.
  'headlesschrome', 'phantomjs', 'puppeteer', 'playwright', 'selenium',
  'python-requests', 'httpclient', 'okhttp', 'axios', 'node-fetch',
  'curl/', 'wget', 'libwww', 'lighthouse', 'pagespeed',
  // This store's own probes and healthchecks.
  'xdipx-',
]

/**
 * True when the user-agent looks automated. An absent or empty user-agent also
 * counts: no real browser omits it, and a blank UA is the cheapest possible
 * crawler disguise.
 */
export function isCrawlerUserAgent(ua: string | null | undefined): boolean {
  if (!ua) return true
  const s = ua.toLowerCase().trim()
  if (s.length === 0) return true
  return CRAWLER_TOKENS.some(t => s.includes(t))
}

/** Convenience wrapper for a Request. */
export function isCrawlerRequest(request: Request): boolean {
  return isCrawlerUserAgent(request.headers.get('user-agent'))
}
