/**
 * User-agent crawler detection, for deciding whether a request deserves paid
 * personalization.
 *
 * This is NOT access control. Crawlers are welcome on the storefront and must
 * keep getting fully rendered pages, so nothing here blocks a request — that is
 * what `botid.server.ts` is for, and it returns a 403, which would be exactly
 * the wrong answer on a PDP we want indexed.
 *
 * WHY IT EXISTS. The PDP's contextual Emma aside is generated by Haiku when the
 * visitor has something to personalize against (a cart, browse history, or an
 * account). The browse history comes from a cookie the PDP itself sets, so a
 * crawler that retains cookies accumulates one and starts looking personalized:
 * on the night of 2026-07-21 something walked 2,709 distinct products and spent
 * 3,566 Haiku calls doing it, against a site seeing about 26 human sessions a
 * week.
 *
 * Two numbers in the original version of this comment were wrong, and they are
 * corrected here because they were quoted onward into commit messages: measured
 * against `api_token_log`, `emma-aside` is about 27% of metered spend over the
 * last 30 days ($20.15), not 47% and not $40/month.
 *
 * WHAT THIS ALONE DOES NOT DO. A scraper sending a stock Chrome user-agent is
 * not caught by anything in this file, and the burst pattern did continue after
 * this gate deployed. It is one of three layers; the other two live at the call
 * site (`_layout.products.$slug.tsx`: a two-product browse threshold and an IP
 * rate limit) and in `emma-aside.server.ts` (`DAILY_BUDGET_CEIL`, the only one
 * that cannot be defeated by disguise).
 *
 * Nothing is lost by skipping it. The server-rendered HTML already contains
 * `emmaAsideStatic` (the approved admin aside, or the per-product template
 * fallback), which is the copy crawlers should be indexing anyway: it is stable
 * across renders, where a per-visitor generation is not.
 */

/**
 * Substrings that identify automated clients, lowercased. Deliberately broad on
 * the generic tokens (`bot`, `crawler`, `spider`) because a false positive
 * costs a personalized sentence while a false negative costs money on every
 * page of a catalog walk.
 */
const CRAWLER_TOKENS: readonly string[] = [
  'bot', 'crawler', 'spider', 'crawling',
  'slurp', 'archiver', 'scraper', 'fetcher', 'monitor',
  // Named crawlers whose UA does not always carry a generic token.
  'googlebot', 'bingbot', 'yandex', 'duckduckbot', 'baiduspider',
  'applebot', 'facebookexternalhit', 'ia_archiver', 'semrush', 'ahrefs',
  'mj12', 'dotbot', 'petalbot', 'bytespider', 'gptbot', 'claudebot',
  'ccbot', 'perplexitybot', 'chatgpt-user', 'oai-searchbot', 'anthropic-ai',
  // Headless and scripted clients.
  'headlesschrome', 'phantomjs', 'puppeteer', 'playwright', 'selenium',
  'python-requests', 'httpclient', 'okhttp', 'axios', 'node-fetch',
  'curl/', 'wget', 'libwww', 'lighthouse', 'pagespeed',
  // This store's own probes and healthchecks.
  'xdipx-',
]

/**
 * True when the user-agent looks automated. An absent or empty user-agent also
 * counts: no real browser omits it, and a blank UA is the cheapest possible
 * crawler disguise.
 */
export function isCrawlerUserAgent(ua: string | null | undefined): boolean {
  if (!ua) return true
  const s = ua.toLowerCase().trim()
  if (s.length === 0) return true
  return CRAWLER_TOKENS.some(t => s.includes(t))
}

/** Convenience wrapper for a Request. */
export function isCrawlerRequest(request: Request): boolean {
  return isCrawlerUserAgent(request.headers.get('user-agent'))
}

/**
 * How many *other* products a visitor must have browsed before browse history
 * alone earns a paid generation.
 *
 * It was 1, which meant the second page a cookie-retaining client loaded
 * already qualified, and every page after that. That is indistinguishable from
 * a catalog walk. Two is the smallest value that requires a client to have
 * actually moved around the store rather than merely kept a cookie.
 */
export const MIN_BROWSE_FOR_PAID_ASIDE = 2

export interface PaidAsideSignals {
  /** The user-agent looked automated. */
  looksAutomated: boolean
  /** There is a cart cookie. */
  hasCart: boolean
  /** Distinct OTHER products in the browse cookie (excludes the current one). */
  browseCount: number
  /** A customer account is attached to the session. */
  isLoggedIn: boolean
}

/**
 * Whether a request has earned a paid, personalized aside. Pure, so the rule is
 * testable without a Request, a cookie jar, or KV.
 *
 * A cart or a logged-in account is strong evidence of a human and short-circuits
 * the browse threshold: both are expensive for a crawler to fake and neither is
 * a side effect of merely loading pages, which is the property browse history
 * lacks.
 *
 * This is the qualification rule only. The caller still applies an IP rate limit
 * on top, and `DAILY_BUDGET_CEIL` in emma-aside.server.ts is the hard stop.
 */
export function qualifiesForPaidAside(s: PaidAsideSignals): boolean {
  if (s.looksAutomated) return false
  if (s.hasCart || s.isLoggedIn) return true
  return s.browseCount >= MIN_BROWSE_FOR_PAID_ASIDE
}
