/**
 * Cart-drawer contextual Emma aside — 1-2 sentence editorial aside generated by
 * Haiku with aggressive KV caching and a template fallback.
 *
 * Mirrors app/lib/emma-aside.server.ts (PDP variant); see that file for the
 * rationale behind the cache-key shape, daily ceiling, and stampede lock.
 *
 * Flow:
 *   1. Compute cache key from (variant, userBucket, cartHash, searchHash, subtotalBand)
 *   2. On hit: return cached text
 *   3. On miss: check daily-count ceiling → if over, fallback
 *   4. Claim a short stampede lock → if already locked, fallback for this render
 *   5. Call Haiku with a tight user prompt; 2.5s timeout
 *   6. Store result in KV (24h); release lock; return
 *   7. Any error along the way → template fallback (bodyForVariant), never blank
 */

import { createHash } from 'node:crypto'
import { kvGet, kvSet, kvIncr, kvDel, KV_KEYS } from './kv.server'
import { BRAND_VOICE_SYSTEM_PROMPT, generateWithSystem } from './claude.server'
import { bodyForVariant } from './emma-cart.server'
import type { EmmaCartVariant } from '~/types'

const HAIKU_TIMEOUT_MS  = 2500
const CACHE_TTL_SECONDS = 60 * 60 * 24        // 24h
const LOCK_TTL_SECONDS  = 3
const MAX_OUTPUT_TOKENS = 120
const DAILY_BUDGET_CEIL = 2000                // fallback-only after this many gens/day

const ASIDE_SYSTEM = `${BRAND_VOICE_SYSTEM_PROMPT}

You're writing ONE aside at the top of the cart drawer. Strict rules:
- 1-2 sentences, max 28 words total.
- React to what's ACTUALLY in the cart — not a generic greeting.
- If you see a pairing angle (complementary items), use it. Otherwise riff on context (free-ship-close, gift, repeat).
- Never say "Buy now" / "checkout now" / mention timers or "until midnight".
- Never quote the cart back verbatim ("I see you have X" = banned).
- Plain text. No markdown. No quotation marks wrapping the aside. Optional ♥ at end.`

// ── Types ────────────────────────────────────────────────────────────────────

export interface EmmaCartAsideLine {
  variantId:   string
  title:       string
  productType: string | null
  quantity:    number
  price:       number
}

export interface EmmaCartAsideArgs {
  variant:          EmmaCartVariant
  cartLines:        EmmaCartAsideLine[]
  subtotal:         number
  freeShipGap:      number
  firstName:        string | null
  orderCount:       number
  recentCategories: string[]
  lastSearchQuery:  string | null
  isGift:           boolean
  hasSubscription:  boolean
  userGid:          string | null
}

export interface EmmaCartAsideResult {
  text:   string
  source: 'cache' | 'claude' | 'fallback'
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function shortHash(input: string): string {
  return createHash('sha1').update(input).digest('hex').slice(0, 8)
}

function hashCartLines(lines: EmmaCartAsideLine[]): string {
  if (lines.length === 0) return '0'
  const sorted = lines
    .map(l => `${l.variantId}:${l.quantity}`)
    .sort()
    .join('|')
  return shortHash(sorted)
}

function hashSearch(query: string | null): string {
  if (!query) return '0'
  return shortHash(query.toLowerCase().trim())
}

function userBucketFor(gid: string | null): string {
  if (!gid) return 'guest'
  return `u:${shortHash(gid)}`
}

function subtotalBandFor(subtotal: number): number {
  // $10 bands — identical carts with ±$9 swings collapse to the same key.
  return Math.floor(subtotal / 10) * 10
}

function utcDateKey(): string {
  return new Date().toISOString().slice(0, 10)
}

function buildUserPrompt(args: EmmaCartAsideArgs): string {
  const lines: string[] = []

  const cartDesc = args.cartLines
    .map(l => {
      const type = l.productType ? ` (${l.productType})` : ''
      const qty  = l.quantity > 1 ? ` x${l.quantity}` : ''
      return `${l.title}${type}${qty}`
    })
    .join(', ')
  lines.push(`In their cart: ${cartDesc}`)
  lines.push(`Subtotal: $${args.subtotal.toFixed(2)}`)

  if (args.freeShipGap > 0) {
    lines.push(`$${args.freeShipGap.toFixed(2)} from free shipping.`)
  } else {
    lines.push(`Free shipping unlocked.`)
  }

  lines.push(`Variant angle: ${args.variant}.`)

  if (args.firstName) lines.push(`First name: ${args.firstName}.`)
  if (args.orderCount > 0) lines.push(`Repeat customer — ${args.orderCount} past orders.`)
  if (args.recentCategories.length > 0) {
    lines.push(`Past purchase categories: ${args.recentCategories.join(', ')}.`)
  }
  if (args.lastSearchQuery) {
    lines.push(`Recently searched: "${args.lastSearchQuery}".`)
  }
  if (args.isGift) lines.push(`This reads as a gift cart.`)
  if (args.hasSubscription) lines.push(`Cart includes a subscription line.`)

  lines.push('')
  lines.push('Write the aside.')
  return lines.join('\n')
}

function cleanOutput(raw: string): string {
  let out = raw.trim()
  out = out.replace(/^```[\w]*\n?/i, '').replace(/\n?```$/i, '').trim()
  if ((out.startsWith('"') && out.endsWith('"')) || (out.startsWith('“') && out.endsWith('”'))) {
    out = out.slice(1, -1).trim()
  }
  out = out.replace(/^[-–—•\s]+/, '').trim()
  return out
}

function fallbackCopy(args: EmmaCartAsideArgs): string {
  return bodyForVariant(args.variant, {
    firstName: args.firstName,
    remaining: args.freeShipGap,
  })
}

// ── Public API ───────────────────────────────────────────────────────────────

export async function getEmmaCartAside(args: EmmaCartAsideArgs): Promise<EmmaCartAsideResult> {
  if (args.cartLines.length === 0) {
    // No cart contents → nothing for Emma to riff on; deterministic copy is fine.
    return { text: fallbackCopy(args), source: 'fallback' }
  }

  const cartHash   = hashCartLines(args.cartLines)
  const searchHash = hashSearch(args.lastSearchQuery)
  const userBucket = userBucketFor(args.userGid)
  const band       = subtotalBandFor(args.subtotal)
  const cacheKey   = KV_KEYS.emmaCartAside(args.variant, userBucket, cartHash, searchHash, band)

  // 1. Cache hit
  try {
    const cached = await kvGet<string>(cacheKey)
    if (cached && typeof cached === 'string' && cached.length > 0) {
      return { text: cached, source: 'cache' }
    }
  } catch {
    // KV read failed — continue to generation path
  }

  // 2. Daily budget ceiling
  try {
    const countKey = KV_KEYS.emmaCartAsideDailyCount(utcDateKey())
    const todayCount = await kvGet<number>(countKey)
    if (typeof todayCount === 'number' && todayCount >= DAILY_BUDGET_CEIL) {
      return { text: fallbackCopy(args), source: 'fallback' }
    }
  } catch { /* non-fatal */ }

  // 3. Stampede lock — keyed on cart signature so unrelated carts don't block each other.
  const lockKey = KV_KEYS.emmaCartAsideLock(cartHash)
  try {
    const existingLock = await kvGet<number>(lockKey)
    const isFresh      = typeof existingLock === 'number' && Date.now() - existingLock < LOCK_TTL_SECONDS * 1000
    if (isFresh) {
      return { text: fallbackCopy(args), source: 'fallback' }
    }
    await kvSet(lockKey, Date.now(), LOCK_TTL_SECONDS)
  } catch { /* non-fatal — proceed without lock */ }

  // 4. Call Haiku
  try {
    const userPrompt = buildUserPrompt(args)
    const raw = await generateWithSystem({
      system:    ASIDE_SYSTEM,
      user:      userPrompt,
      maxTokens: MAX_OUTPUT_TOKENS,
      timeoutMs: HAIKU_TIMEOUT_MS,
    })
    const text = cleanOutput(raw)
    if (!text) throw new Error('Empty Claude response')

    // 5. Cache + bump daily count
    try {
      await kvSet(cacheKey, text, CACHE_TTL_SECONDS)
      await kvIncr(KV_KEYS.emmaCartAsideDailyCount(utcDateKey()))
    } catch { /* non-fatal */ }

    try { await kvDel(lockKey) } catch { /* non-fatal */ }

    return { text, source: 'claude' }
  } catch (err) {
    console.warn('[emma-cart-aside] generation failed, using fallback:', err instanceof Error ? err.message : err)
    try { await kvDel(lockKey) } catch { /* non-fatal */ }
    return { text: fallbackCopy(args), source: 'fallback' }
  }
}
