/**
 * PDP contextual Emma aside — 1-2 sentence editorial aside generated by Haiku
 * with aggressive KV caching and a template fallback. Budget target ~$15-30/mo
 * enforced via the cache key collapsing guest/empty-input traffic to a single
 * key per product.
 *
 * Flow:
 *   1. Compute cache key from (productId, userBucket, cartHash, browseHash)
 *   2. On hit: return cached text (most traffic)
 *   3. On miss: check daily-count ceiling → if over, fallback
 *   4. Claim a short stampede lock → if already locked, fallback for this render
 *   5. Call Haiku with a tight user prompt; 1.5s timeout
 *   6. Store result in KV (24h); release lock; return
 *   7. Any error along the way → template fallback, never blank
 */

import { createHash } from 'node:crypto'
import { kvGet, kvSet, kvIncr, kvDel, KV_KEYS } from './kv.server'
import { BRAND_VOICE_SYSTEM_PROMPT, generateWithSystem } from './claude.server'
import { getFallbackAside } from './emma-aside-templates.server'
import type { Deal } from '~/types'

const HAIKU_TIMEOUT_MS  = 3500
const CACHE_TTL_SECONDS = 60 * 60 * 24        // 24h
const LOCK_TTL_SECONDS  = 3
const MAX_OUTPUT_TOKENS = 240
const DAILY_BUDGET_CEIL = 5000                 // fallback-only after this many gens/day

const ASIDE_SYSTEM = `${BRAND_VOICE_SYSTEM_PROMPT}

You're writing ONE contextual aside for the product detail page. Strict rules:
- 2-4 sentences, max 56 words total.
- Do not start the aside with your own name or "Emma —"; the UI already shows your avatar and name.
- Sound like you're reacting to this exact person on this exact page — not reading a press release.
- Never say "Buy now". Never mention timers or urgency.
- Never quote the context back verbatim ("I see you have X in your cart" = banned).
- You can riff on what's in their cart / what they've been browsing / how this pairs — pick the most interesting angle and develop it; don't stack three at once.
- Plain text. No markdown. No quotation marks wrapping the whole aside. Optional ♥ at the end.`

// ── Types ────────────────────────────────────────────────────────────────────

export interface EmmaAsideArgs {
  product:           Pick<Deal, 'id' | 'shopifyProductId' | 'seoTitle' | 'brand' | 'tagline' | 'productTypeDial'>
  cartLines:         Array<{ title: string; quantity: number }>
  browseProducts:    Array<{ title: string }>
  pairsWithProducts: Array<{ title: string }>
  userGid:           string | null
}

export interface EmmaAsideResult {
  text:   string
  source: 'cache' | 'claude' | 'fallback'
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function shortHash(input: string): string {
  return createHash('sha1').update(input).digest('hex').slice(0, 8)
}

function hashTitles(items: Array<{ title: string }>): string {
  if (items.length === 0) return '0'
  const sorted = items.map(i => i.title.toLowerCase().trim()).sort().join('|')
  return shortHash(sorted)
}

function userBucketFor(gid: string | null): string {
  if (!gid) return 'guest'
  return `u:${shortHash(gid)}`
}

function utcDateKey(): string {
  return new Date().toISOString().slice(0, 10) // YYYY-MM-DD
}

function buildUserPrompt(args: EmmaAsideArgs): string {
  const { product, cartLines, browseProducts, pairsWithProducts } = args
  const lines: string[] = []
  lines.push(`Product: ${product.seoTitle} (${product.productTypeDial ?? 'accessory'}, ${product.brand}).`)
  if (product.tagline) lines.push(`Tagline: ${product.tagline}`)
  if (cartLines.length > 0) {
    lines.push(`Already in their bag: ${cartLines.map(c => c.title).join(', ')}`)
  }
  if (browseProducts.length > 0) {
    lines.push(`Also recently browsing: ${browseProducts.map(b => b.title).join(', ')}`)
  }
  if (pairsWithProducts.length > 0) {
    lines.push(`Plays well with: ${pairsWithProducts.map(p => p.title).join(', ')}`)
  }
  lines.push('')
  lines.push('Write the aside.')
  return lines.join('\n')
}

function cleanOutput(raw: string): string {
  // Strip surrounding quotes, leading bullet markers, stray code fences,
  // and any leading "Emma —" / "Emma -" / "Emma:" the model may add despite
  // instructions (the UI already attributes via avatar + name).
  let out = raw.trim()
  out = out.replace(/^```[\w]*\n?/i, '').replace(/\n?```$/i, '').trim()
  if ((out.startsWith('"') && out.endsWith('"')) || (out.startsWith('“') && out.endsWith('”'))) {
    out = out.slice(1, -1).trim()
  }
  out = out.replace(/^[-–—•\s]+/, '').trim()
  out = out.replace(/^emma\s*[—–\-:]\s*/i, '').trim()
  return out
}

// ── Public API ───────────────────────────────────────────────────────────────

export async function getEmmaAside(args: EmmaAsideArgs): Promise<EmmaAsideResult> {
  const { product } = args
  const cartHash   = hashTitles(args.cartLines)
  const browseHash = hashTitles(args.browseProducts)
  const userBucket = userBucketFor(args.userGid)
  const cacheKey   = KV_KEYS.emmaAside(product.shopifyProductId, userBucket, cartHash, browseHash)

  // 1. Cache hit
  try {
    const cached = await kvGet<string>(cacheKey)
    if (cached && typeof cached === 'string' && cached.length > 0) {
      return { text: cached, source: 'cache' }
    }
  } catch {
    // KV read failed — continue to generation path
  }

  // 2. Daily budget ceiling
  try {
    const countKey = KV_KEYS.emmaAsideDailyCount(utcDateKey())
    const todayCount = await kvGet<number>(countKey)
    if (typeof todayCount === 'number' && todayCount >= DAILY_BUDGET_CEIL) {
      return { text: getFallbackAside(product), source: 'fallback' }
    }
  } catch { /* non-fatal */ }

  // 3. Stampede lock (per-product; prevents concurrent cache-miss bursts on a hot product).
  // Timestamp-based so stale locks self-heal even when the KV backend (in-memory dev
  // fallback) can't enforce TTL on its own.
  const lockKey = KV_KEYS.emmaAsideLock(product.shopifyProductId)
  try {
    const existingLock = await kvGet<number>(lockKey)
    const isFresh      = typeof existingLock === 'number' && Date.now() - existingLock < LOCK_TTL_SECONDS * 1000
    if (isFresh) {
      return { text: getFallbackAside(product), source: 'fallback' }
    }
    await kvSet(lockKey, Date.now(), LOCK_TTL_SECONDS)
  } catch { /* non-fatal — proceed without lock */ }

  // 4. Call Haiku
  try {
    const userPrompt = buildUserPrompt(args)
    const raw = await generateWithSystem({
      system:    ASIDE_SYSTEM,
      user:      userPrompt,
      maxTokens: MAX_OUTPUT_TOKENS,
      timeoutMs: HAIKU_TIMEOUT_MS,
      caller:    'emma-aside',
      productId: product.shopifyProductId,
    })
    const text = cleanOutput(raw)
    if (!text) throw new Error('Empty Claude response')

    // 5. Cache + bump daily count
    try {
      await kvSet(cacheKey, text, CACHE_TTL_SECONDS)
      await kvIncr(KV_KEYS.emmaAsideDailyCount(utcDateKey()))
    } catch { /* non-fatal */ }

    // Release lock now that generation finished (dev-safe: in-memory KV ignores TTL).
    try { await kvDel(lockKey) } catch { /* non-fatal */ }

    return { text, source: 'claude' }
  } catch (err) {
    console.warn('[emma-aside] generation failed, using fallback:', err instanceof Error ? err.message : err)
    try { await kvDel(lockKey) } catch { /* non-fatal */ }
    return { text: getFallbackAside(product), source: 'fallback' }
  }
}
