// Document type so individual rails can exist as drafts (drafts.<id>) and be
// published independently. References to live rails are embedded in
// homepageSections.sections[] and productPage.contentBlocks[].
export default {
  name: 'emmaCuratedRail',
  title: 'Emma Curated Rail',
  type: 'document',
  fields: [
    { name: 'active', title: 'Active', type: 'boolean', initialValue: true },
    { name: 'order',  title: 'Order',  type: 'number',  initialValue: 50, hidden: true },

    // ─── Editorial copy ──────────────────────────────────────────────
    { name: 'heading', title: 'Heading', type: 'string' },
    { name: 'eyebrow', title: 'Eyebrow', type: 'string' },
    {
      name: 'emmaAside',
      title: 'Emma Aside',
      type: 'text',
      rows: 2,
      description: "Emma's first-person aside above the heading (e.g. 'been pairing these all month')",
    },

    // ─── Products (manual handles only — admin can swap individuals) ─
    {
      name: 'productHandles',
      title: 'Product Handles',
      type: 'array',
      of: [
        {
          type: 'object',
          name: 'productRef',
          fields: [
            {
              name: 'handle',
              title: 'Product Handle',
              type: 'string',
              description: 'Shopify product handle (the URL slug)',
            },
          ],
          preview: {
            select: { title: 'handle' },
            prepare({ title }) {
              return { title: title ?? '(empty)' }
            },
          },
        },
      ],
      description: 'Products in this rail. Generated by Emma; admin can add/remove/swap.',
    },

    // ─── Layout & Style (mirrors productCarousel) ────────────────────
    {
      name: 'layout',
      title: 'Layout',
      type: 'string',
      options: {
        list: [
          { title: 'Carousel (horizontal scroll)', value: 'carousel' },
          { title: 'Grid (2 columns mobile, 4 desktop)', value: 'grid' },
          { title: 'Grid (2 columns mobile, 3 desktop)', value: 'grid-3' },
        ],
        layout: 'radio',
      },
      initialValue: 'carousel',
    },
    {
      name: 'bgStyle',
      title: 'Background',
      type: 'string',
      options: {
        list: [
          { title: 'White',    value: 'white' },
          { title: 'Cream',    value: 'cream' },
          { title: 'Mist',     value: 'mist' },
          { title: 'Charcoal', value: 'charcoal' },
          { title: 'Purple',   value: 'purple' },
        ],
      },
      initialValue: 'cream',
    },

    // ─── CTA ─────────────────────────────────────────────────────────
    { name: 'ctaLink',  title: 'CTA Link',  type: 'string' },
    { name: 'ctaLabel', title: 'CTA Label', type: 'string', initialValue: 'See all →' },

    // ─── Provenance / lifecycle ──────────────────────────────────────
    {
      name: 'target',
      title: 'Target Surface',
      type: 'string',
      options: {
        list: [
          { title: 'Homepage', value: 'homepage' },
          { title: 'PDP',      value: 'pdp' },
        ],
        layout: 'radio',
      },
      initialValue: 'homepage',
    },
    {
      name: 'status',
      title: 'Status',
      type: 'string',
      options: {
        list: [
          { title: 'Draft',    value: 'draft' },
          { title: 'Approved', value: 'approved' },
          { title: 'Live',     value: 'live' },
          { title: 'Archived', value: 'archived' },
        ],
        layout: 'radio',
      },
      initialValue: 'draft',
      description: 'Only "live" rails render on the storefront.',
    },
    {
      name: 'sourceDealId',
      title: 'Source Deal ID',
      type: 'string',
      description: 'Shopify product ID of the deal that generated this rail.',
      readOnly: true,
    },
    {
      name: 'generatedAt',
      title: 'Generated At',
      type: 'datetime',
      readOnly: true,
    },
    {
      name: 'rationale',
      title: "Emma's Rationale",
      type: 'text',
      rows: 3,
      description: 'Why Emma chose these products. Studio + admin only — never rendered on storefront.',
    },
  ],
  preview: {
    select: {
      title: 'heading',
      target: 'target',
      status: 'status',
      active: 'active',
      order: 'order',
    },
    prepare({ title, target, status, active, order }) {
      return {
        title: title ?? '(no heading)',
        subtitle: `♥ ${target ?? '?'} · ${status ?? 'draft'} · ${active ? 'Visible' : 'Hidden'}`,
      }
    },
  },
}
