/**
 * api.video-preview.$token.tsx
 *
 * Streams a rendered preview video from the .video-previews/ temp dir.
 * Tokens are 16-byte hex strings generated by api.generate-video.tsx.
 */

import type { LoaderFunctionArgs } from 'react-router'
import { requireAdmin } from '~/lib/session.server'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

const PREVIEW_DIR = join(process.cwd(), '.video-previews')

export async function loader({ request, params }: LoaderFunctionArgs) {
  await requireAdmin(request)

  const token = params['token']
  // Validate token is safe hex string — no path traversal
  if (!token || !/^[a-f0-9]{32}$/.test(token)) {
    return new Response('Invalid token', { status: 400 })
  }

  const filePath = join(PREVIEW_DIR, `${token}.mp4`)
  if (!existsSync(filePath)) {
    return new Response('Preview not found or expired', { status: 404 })
  }

  const buffer = readFileSync(filePath)
  return new Response(buffer, {
    headers: {
      'Content-Type': 'video/mp4',
      'Content-Length': String(buffer.length),
      'Cache-Control': 'no-store',
    },
  })
}
