/**
 * Ticket #3451 — one-time backfill for the "Pairs with" storefront surface.
 *
 * PairsWith.tsx, the loader branch in _layout.products.$slug.tsx, and the
 * xdipx.accessory_product_ids / xdipx.pairing_why writers in shopify.server.ts
 * are all already live. The surface just has no data: as of 2026-08-19,
 * accessory_product_ids is non-empty on 10/4,691 products and pairing_why on 6.
 * This script fills both for a top slice of anchor SKUs.
 *
 * Anchor selection: ACTIVE products ranked by xdipx.deal_score (desc) first
 * — but deal_score turns out to be a Nalpac-feed-era artifact populated on
 * only ~9 of 4,730 active products, so it can't carry the ranking alone.
 * Tie-break (i.e. the effective primary signal for the other ~4,721) is
 * Shopify's own updatedAt (desc): most-recently-touched product as the best
 * available proxy for "currently merchandised" absent a real popularity/
 * sales-rank field. Restricted to product_type_dial values with a defined
 * complement mapping below (novelty and book-media are skipped — no natural
 * toy-adjacent accessory), top ~200 taken. Products that already carry BOTH
 * accessory_product_ids and pairing_why are skipped by default (fill-gaps);
 * pass --force to overwrite.
 *
 * Complement map: keyed on product_type_dial (+ product_subtype_dial where
 * it sharpens the pick, e.g. lube's "toy-cleaner" subtype for a cleaner).
 * Editorial judgment, not automated inference — see COMPLEMENTS below.
 *
 * Writes:
 *   1. xdipx.accessory_product_ids (json) via updateProductMetafield — the
 *      curated accessory GID list, in display order.
 *   2. xdipx.pairing_why (json) via setPairingWhy — Emma-voice copy per
 *      accessory GID, generated by generatePairingWhyOnly() in
 *      claude.server.ts, which is a narrow harness around the EXISTING
 *      propose_pairing_why tool + executeRailTool dispatcher from
 *      emma-rail-tools.server.ts (same tool generateRails() uses). No new
 *      copy-generation logic — this only restricts the tool list so the
 *      model can't also propose rails (which would leave unreviewed Sanity
 *      rail drafts for every anchor, out of scope for a metafield backfill).
 *
 * Usage:
 *   npx tsx scripts/backfill-pairswith.ts                  # dry-run, top 200, prints plan
 *   npx tsx scripts/backfill-pairswith.ts --limit=10        # dry-run, first 10 anchors only
 *   npx tsx scripts/backfill-pairswith.ts --apply            # writes to Shopify + Anthropic spend
 *   npx tsx scripts/backfill-pairswith.ts --apply --limit=10 # smoke-test a live run
 *   npx tsx scripts/backfill-pairswith.ts --apply --force    # overwrite anchors that already have data
 *
 * Exit code: 0 on clean run, 1 if any anchor errored.
 */
// MUST be the first import — populates process.env (with override) before any
// downstream module reads it at evaluation time.
import './_load-env'
import { adminGraphQL, updateProductMetafield, setPairingWhy } from '../app/lib/shopify.server'
import { generatePairingWhyOnly } from '../app/lib/claude.server'
import type { ProductTypeDial } from '../app/types'

// ─── Args ─────────────────────────────────────────────────────────────────

interface Args {
  apply: boolean
  force: boolean
  limit: number
}

function parseArgs(argv: string[]): Args {
  const args = argv.slice(2)
  const has = (flag: string) => args.includes(flag)
  const valOf = (prefix: string) => {
    const arg = args.find(a => a.startsWith(`${prefix}=`))
    return arg ? arg.slice(prefix.length + 1) : undefined
  }
  const limit = Number(valOf('--limit') ?? '200')
  return {
    apply: has('--apply'),
    force: has('--force'),
    limit: Number.isFinite(limit) && limit > 0 ? limit : 200,
  }
}

// ─── Complement map — editorial judgment, keyed on product_type_dial ───────
// (+ product_subtype_dial where it sharpens the pick). novelty and
// book-media are intentionally absent — no natural toy-adjacent accessory.

interface ComplementSpec {
  dial: ProductTypeDial
  subtype?: string
}

const COMPLEMENTS: Partial<Record<ProductTypeDial, ComplementSpec[]>> = {
  vibrator:      [{ dial: 'lube', subtype: 'water-based' }, { dial: 'lube', subtype: 'toy-cleaner' }],
  dildo:         [{ dial: 'lube', subtype: 'water-based' }, { dial: 'lube', subtype: 'toy-cleaner' }],
  anal:          [{ dial: 'lube', subtype: 'anal' },        { dial: 'lube', subtype: 'toy-cleaner' }],
  stroker:       [{ dial: 'lube', subtype: 'water-based' }, { dial: 'lube', subtype: 'toy-cleaner' }],
  bondage:       [{ dial: 'wellness', subtype: 'aftercare' }, { dial: 'lube', subtype: 'water-based' }],
  'cock-ring':   [{ dial: 'lube', subtype: 'water-based' }, { dial: 'condom' }],
  couples:       [{ dial: 'lube', subtype: 'water-based' }, { dial: 'wear' }],
  harness:       [{ dial: 'extender' }, { dial: 'lube', subtype: 'water-based' }],
  extender:      [{ dial: 'harness' }, { dial: 'lube', subtype: 'water-based' }],
  pump:          [{ dial: 'lube', subtype: 'water-based' }, { dial: 'wellness', subtype: 'aftercare' }],
  lube:          [{ dial: 'vibrator' }, { dial: 'wellness', subtype: 'aftercare' }],
  massage:       [{ dial: 'wellness', subtype: 'aftercare' }, { dial: 'vibrator' }],
  enhancer:      [{ dial: 'lube', subtype: 'water-based' }, { dial: 'wellness', subtype: 'aftercare' }],
  wear:          [{ dial: 'vibrator' }, { dial: 'lube', subtype: 'water-based' }],
  condom:        [{ dial: 'lube', subtype: 'water-based' }],
  wellness:      [{ dial: 'vibrator' }, { dial: 'lube', subtype: 'water-based' }],
  'sex-machine': [{ dial: 'lube', subtype: 'water-based' }, { dial: 'wellness', subtype: 'aftercare' }],
}

// ─── Catalog index ────────────────────────────────────────────────────────

interface IndexedProduct {
  gid: string
  numericId: string
  handle: string
  title: string
  vendor: string
  productTypeDial: ProductTypeDial | ''
  productSubtypeDial: string
  dealScore: number | null
  updatedAt: string
  tagline: string
  category: string[]
  hasAccessoryIds: boolean
  hasPairingWhy: boolean
}

interface AdminMetafieldNode { key: string; value: string }
interface AdminProductNode {
  id: string
  handle: string
  title: string
  vendor: string
  status: string
  updatedAt: string
  xdipxMf: { nodes: AdminMetafieldNode[] }
  customMf: { nodes: AdminMetafieldNode[] }
}
interface PageInfo { hasNextPage: boolean; endCursor: string | null }
type FetchResult = { products: { pageInfo: PageInfo; nodes: AdminProductNode[] } }

async function fetchCatalogIndex(): Promise<IndexedProduct[]> {
  const out: IndexedProduct[] = []
  let cursor: string | null = null
  let hasNextPage = true
  let page = 0

  while (hasNextPage) {
    page++
    const data: FetchResult = await adminGraphQL<FetchResult>(`
      query BackfillPairsWithIndex($first: Int!, $after: String) {
        products(first: $first, after: $after, query: "status:active") {
          pageInfo { hasNextPage endCursor }
          nodes {
            id handle title vendor status updatedAt
            xdipxMf: metafields(namespace: "xdipx", first: 100) { nodes { key value } }
            customMf: metafields(namespace: "custom", first: 5) { nodes { key value } }
          }
        }
      }
    `, { first: 50, after: cursor })

    const conn = data.products
    hasNextPage = conn.pageInfo.hasNextPage
    cursor = conn.pageInfo.endCursor

    for (const node of conn.nodes) {
      const xVal = (key: string) => node.xdipxMf.nodes.find(m => m.key === key)?.value ?? ''
      const cVal = (key: string) => node.customMf.nodes.find(m => m.key === key)?.value ?? ''
      const dealScoreRaw = xVal('deal_score')
      const dealScore = dealScoreRaw ? parseFloat(dealScoreRaw) : null
      let category: string[] = []
      const categoryRaw = xVal('category')
      if (categoryRaw.trim().startsWith('[')) {
        try {
          const parsed = JSON.parse(categoryRaw)
          if (Array.isArray(parsed)) category = parsed.filter((s): s is string => typeof s === 'string')
        } catch { /* ignore malformed */ }
      }
      let hasAccessoryIds = false
      const accessoryRaw = xVal('accessory_product_ids')
      if (accessoryRaw.trim().startsWith('[')) {
        try {
          const parsed = JSON.parse(accessoryRaw)
          hasAccessoryIds = Array.isArray(parsed) && parsed.length > 0
        } catch { /* ignore malformed */ }
      }
      let hasPairingWhy = false
      const pairingRaw = xVal('pairing_why')
      if (pairingRaw.trim().startsWith('{')) {
        try {
          const parsed = JSON.parse(pairingRaw)
          hasPairingWhy = parsed && typeof parsed === 'object' && Object.keys(parsed).length > 0
        } catch { /* ignore malformed */ }
      }

      out.push({
        gid:       node.id,
        numericId: node.id.replace('gid://shopify/Product/', ''),
        handle:    node.handle,
        title:     node.title,
        vendor:    node.vendor,
        productTypeDial:    (xVal('product_type_dial') as ProductTypeDial) || '',
        productSubtypeDial: cVal('product_subtype_dial'),
        dealScore,
        updatedAt: node.updatedAt,
        tagline:   xVal('tagline'),
        category,
        hasAccessoryIds,
        hasPairingWhy,
      })
    }

    console.log(`[index] page ${page}: +${conn.nodes.length} products, cumulative=${out.length}`)
  }

  return out
}

// ─── Ranking ──────────────────────────────────────────────────────────────
// xdipx.deal_score desc first (populated on only ~9/4,730 active products —
// a Nalpac-feed-era artifact, not a universal signal), then Shopify's own
// updatedAt desc as the tie-break that does the real ordering work for
// everything else: most-recently-touched product, the best available proxy
// for "currently merchandised" absent a real popularity/sales-rank field.
function rankAnchors(a: IndexedProduct, b: IndexedProduct): number {
  const scoreDiff = (b.dealScore ?? -1) - (a.dealScore ?? -1)
  if (scoreDiff !== 0) return scoreDiff
  return new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()
}

// ─── Complement resolution ────────────────────────────────────────────────

/** Picks the best candidate in `pool` for a ComplementSpec, preferring an
 *  exact subtype match, falling back to dial-only, excluding `excludeGid`s
 *  already chosen for this anchor. Ranks by dealScore desc within a tier. */
function resolveComplement(
  spec: ComplementSpec,
  pool: IndexedProduct[],
  excludeGids: Set<string>,
): IndexedProduct | null {
  const dialMatches = pool.filter(p => p.productTypeDial === spec.dial && !excludeGids.has(p.gid))
  const rank = (list: IndexedProduct[]) => [...list].sort(rankAnchors)

  if (spec.subtype) {
    const subtypeMatches = rank(dialMatches.filter(p => p.productSubtypeDial === spec.subtype))
    if (subtypeMatches.length > 0) return subtypeMatches[0]!
  }
  const fallback = rank(dialMatches)
  return fallback[0] ?? null
}

// ─── Main ─────────────────────────────────────────────────────────────────

async function main() {
  const args = parseArgs(process.argv)
  console.log(`[backfill-pairswith] mode=${args.apply ? 'APPLY' : 'DRY-RUN'} limit=${args.limit} force=${args.force}`)

  console.log('[backfill-pairswith] building catalog index (ACTIVE products, xdipx + custom metafields)...')
  const index = await fetchCatalogIndex()
  console.log(`[backfill-pairswith] indexed ${index.length} active products`)

  const eligible = index.filter(p => p.productTypeDial && COMPLEMENTS[p.productTypeDial])
  console.log(`[backfill-pairswith] ${eligible.length} products have a product_type_dial with a defined complement mapping`)

  const notAlreadyDone = args.force ? eligible : eligible.filter(p => !(p.hasAccessoryIds && p.hasPairingWhy))
  console.log(`[backfill-pairswith] ${notAlreadyDone.length} not already fully covered (accessory_product_ids + pairing_why)`)

  const anchors = [...notAlreadyDone]
    .sort(rankAnchors)
    .slice(0, args.limit)
  console.log(`[backfill-pairswith] selected ${anchors.length} anchor SKU(s) — top by xdipx.deal_score desc, then Shopify updatedAt desc`)

  let written = 0
  let skippedNoComplement = 0
  const errors: Array<{ handle: string; message: string }> = []

  for (let i = 0; i < anchors.length; i++) {
    const anchor = anchors[i]!
    const specs = COMPLEMENTS[anchor.productTypeDial as ProductTypeDial] ?? []
    const excludeGids = new Set<string>([anchor.gid])
    const picks: IndexedProduct[] = []
    for (const spec of specs) {
      const pick = resolveComplement(spec, index, excludeGids)
      if (pick) {
        picks.push(pick)
        excludeGids.add(pick.gid)
      }
    }

    if (picks.length === 0) {
      skippedNoComplement++
      console.log(`  [${i + 1}/${anchors.length}] SKIP ${anchor.handle} (${anchor.productTypeDial}) — no complement candidates found in catalog`)
      continue
    }

    const accessoryIds = picks.map(p => p.gid)
    console.log(
      `  [${i + 1}/${anchors.length}] ${anchor.handle} (${anchor.productTypeDial}, score=${anchor.dealScore ?? 'n/a'}, updated=${anchor.updatedAt.slice(0, 10)}) -> ` +
      picks.map(p => `${p.handle} (${p.productTypeDial}${p.productSubtypeDial ? `:${p.productSubtypeDial}` : ''})`).join(', '),
    )

    if (!args.apply) continue

    try {
      await updateProductMetafield(anchor.gid, 'accessory_product_ids', JSON.stringify(accessoryIds), 'json')

      const { pairingWhy } = await generatePairingWhyOnly({
        anchor: {
          title: anchor.title,
          ...(anchor.vendor ? { brand: anchor.vendor } : {}),
          ...(anchor.category.length ? { category: anchor.category } : {}),
          ...(anchor.tagline ? { tagline: anchor.tagline } : {}),
          ...(anchor.productTypeDial ? { productTypeDial: anchor.productTypeDial } : {}),
        },
        accessories: picks.map(p => ({ id: p.gid, title: p.title, ...(p.vendor ? { brand: p.vendor } : {}) })),
      })

      if (pairingWhy.length > 0) {
        const blurbs: Record<string, string> = {}
        for (const p of pairingWhy) blurbs[p.accessoryProductId] = p.blurb
        await setPairingWhy(anchor.gid, blurbs, { merge: true })
        console.log(`    ✓ wrote accessory_product_ids (${accessoryIds.length}) + pairing_why (${pairingWhy.length})`)
      } else {
        console.log(`    ✓ wrote accessory_product_ids (${accessoryIds.length}); pairing_why generation returned 0 blurbs`)
      }
      written++
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      errors.push({ handle: anchor.handle, message })
      console.error(`    ✗ ${anchor.handle}: ${message}`)
    }
  }

  console.log('')
  console.log('[backfill-pairswith] summary')
  console.log(`  anchors selected:        ${anchors.length}`)
  console.log(`  skipped (no complement): ${skippedNoComplement}`)
  console.log(`  written:                 ${args.apply ? written : '(dry-run — nothing written)'}`)
  console.log(`  errors:                  ${errors.length}`)
  for (const e of errors) console.log(`    - ${e.handle}: ${e.message}`)

  if (errors.length > 0) process.exit(1)
}

main().catch(err => {
  console.error('[backfill-pairswith] fatal:', err)
  process.exit(1)
})
