import { createElement } from 'react'

const RICH_TEXT_BLOCK = {
  type: 'block',
  styles: [
    { title: 'Normal',    value: 'normal' },
    { title: 'Heading 2', value: 'h2'     },
    { title: 'Heading 3', value: 'h3'     },
  ],
  lists: [
    { title: 'Bullet',   value: 'bullet'  },
    { title: 'Numbered', value: 'number'  },
  ],
  marks: {
    decorators: [
      { title: 'Bold',      value: 'strong' },
      { title: 'Italic',    value: 'em'     },
      { title: 'Underline', value: 'underline' },
    ],
    annotations: [
      {
        name: 'link', title: 'Link', type: 'object',
        fields: [{
          name: 'href', title: 'URL', type: 'url',
          // Allow internal relative links; the default url rule gates publish.
          validation: (Rule) => Rule.uri({ allowRelative: true, scheme: ['http', 'https', 'mailto', 'tel'] }),
        }],
      },
    ],
  },
}

export default {
  name: 'productPage',
  title: 'Product Page',
  type: 'document',

  groups: [
    { name: 'product',  title: 'Product',        default: true },
    { name: 'copy',     title: 'Copy & Story'                  },
    { name: 'care',     title: 'Care & Specs'                  },
    { name: 'emma',     title: 'Emma Discovery'                },
    { name: 'ivr',      title: 'IVR / Voice'                   },
    { name: 'bundle',   title: 'Bundle'                        },
    { name: 'faqs',     title: 'FAQs / Q&A'                    },
    { name: 'content',  title: 'Content Blocks'                },
  ],

  // Collapsible legend at the top of the Product tab — explains the field
  // source emojis (🛒 / ✏️ / 🔗) and the readOnly behaviour.
  fieldsets: [
    {
      name: 'legend',
      title: '📋 Field source legend',
      options: { collapsible: true, collapsed: true },
    },
  ],

  fields: [
    // ── Field source legend (collapsible, collapsed by default) ──────────────
    {
      name: 'legendNote',
      title: 'Where each field’s value comes from',
      type: 'string',
      fieldset: 'legend',
      group: 'product',
      readOnly: true,
      hidden: () => false,
      description: [
        '🛒  SHOPIFY-SOURCED',
        '    Mirrored from a Shopify metafield (xdipx.* or product.*) by the orchestrator.',
        '    Read-only here. Edits via API are overwritten by the next backfill.',
        '    →  To change durably: edit in Shopify Admin, then trigger a backfill',
        '       (or wait for the next nightly run).',
        '',
        '✏️  SANITY-ONLY',
        '    No Shopify counterpart.',
        '    •  Auto-generated by Emma (read-only):',
        '         productFaqs · ivrExperience · ivrUseCase · ivrFeatures',
        '    •  Pure editorial (writable):',
        '         bundles · contentBlocks · archived',
        '',
        '🔗  IDENTITY / LINKING',
        '    Auto-managed connection between Shopify and Sanity.',
        '    ⚠  Wrong values break the PDP link or the Shopify push.',
      ].join('\n'),
    },

    // ── Preview image (auto-filled by sync, not shown in form) ───────────────
    {
      name: 'previewImageUrl',
      title: 'Preview Image URL',
      type: 'url',
      hidden: true,
    },

    // ── Internal IDs ────────────────────────────────────────────────────────
    {
      name: 'shopifyHandle',
      title: '🔗 Shopify Handle',
      type: 'string',
      group: 'product',
      description: 'URL slug — auto-filled by the sync script. Changing this breaks the PDP link. 🔗 Identity field.',
      validation: Rule => Rule.required(),
    },
    {
      name: 'shopifyProductId',
      title: '🔗 Shopify Product ID',
      type: 'string',
      group: 'product',
      description: 'Numeric Shopify ID — auto-filled. Used to push changes back to Shopify. 🔗 Identity field.',
      readOnly: true,
    },

    // ── Product Details ──────────────────────────────────────────────────────
    {
      name: 'title',
      title: '🛒 Product Title',
      type: 'string',
      group: 'product',
      description: 'Customer-facing title (may be SEO-augmented from the manufacturer’s original). 🛒 Source: Shopify product.title — edits here are overwritten by the next backfill.',
      readOnly: true,
    },
    {
      name: 'originalTitle',
      title: '🛒 Original Manufacturer Title',
      type: 'string',
      group: 'product',
      description: 'Manufacturer’s verbatim title — kept as the legal/sourcing source-of-truth. 🛒 Source: Shopify metafield `xdipx.original_title`.',
      readOnly: true,
    },
    {
      name: 'vendor',
      title: '🛒 Brand / Vendor',
      type: 'string',
      group: 'product',
      description: '🛒 Source: Shopify product.vendor.',
      readOnly: true,
    },
    {
      name: 'tags',
      title: '🛒 Tags (editorial sub-categories)',
      type: 'array',
      group: 'product',
      description: 'Editorial sub-category labels from the Nalpac feed (e.g. "Top 100 Items", "Restraints"). NOT a full mirror of Shopify product.tags — Shopify also carries operational tags (brand:*, cat:*, deal-status-*, price:*, nalpac-sku-*) that are intentionally excluded from this Studio view to keep editorial faceting focused. 🛒 Source: Nalpac feed `categories` (passed through bulk-import).',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
      readOnly: true,
    },
    {
      name: 'normalizedTags',
      title: '🤖 Normalized Tags (filter index)',
      type: 'array',
      group: 'product',
      description: 'Canonical slug form of every entry in `tags`, computed via `app/lib/tag-normalize.ts`. Used by /search and /view-all faceted filtering so admin-curated taxonomy values (e.g. `cat:plugs-and-probes`) match real Shopify tags (e.g. "Plugs and Probes"). Derived field — DO NOT edit directly. Populated by sync-products-to-sanity.ts and the backfill-normalized-tags.ts script.',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
      readOnly: true,
      hidden: true,
    },
    {
      name: 'description',
      title: '🛒 Product Description',
      type: 'array',
      group: 'product',
      description: 'Emma’s Take — shown as the product body in Shopify. 🛒 Source: Shopify product.body_html (orchestrator B1).',
      of: [RICH_TEXT_BLOCK],
      readOnly: true,
    },
    {
      name: 'seoTitle',
      title: '🛒 SEO Title',
      type: 'string',
      group: 'product',
      description: 'Overrides the page <title> in Google. Leave blank to use product title. 🛒 Source: Shopify product.seo.title.',
      validation: Rule => Rule.max(70),
      readOnly: true,
    },
    {
      name: 'seoDescription',
      title: '🛒 SEO Description',
      type: 'text',
      group: 'product',
      rows: 3,
      description: '🛒 Source: Shopify metafield `xdipx.seo_meta_description`.',
      validation: Rule => Rule.max(160),
      readOnly: true,
    },

    // ── Copy & Story ─────────────────────────────────────────────────────────
    {
      name: 'tagline',
      title: '🛒 Tagline',
      type: 'string',
      group: 'copy',
      description: 'Short punchy line shown under the product title on the PDP. 🛒 Source: Shopify metafield `xdipx.tagline`.',
      readOnly: true,
    },
    // Phase 1 deprecations (PR#50/#51) — fullStory (B2), worksForHim/Her (B3),
    // and featureBullets are no longer generated. Removed from schema; existing
    // values on legacy docs are ignored by the PDP.
    {
      name: 'moodImageUrl',
      title: '🛒 Mood / Lifestyle Image URL',
      type: 'url',
      group: 'copy',
      description: 'Full URL to a lifestyle image. Renders as PDP hero background. 🛒 Source: Shopify metafield `xdipx.mood_image_url`.',
      readOnly: true,
    },

    // ── Care & Specs (mirrored from Shopify metafields by the orchestrator) ─
    // Source-of-truth lives on Shopify (xdipx.care_instructions, .specifications,
    // .box_contents). These fields are populated by the import/backfill pipeline
    // so the productPage doc reflects everything the PDP renders. Edits made
    // here are reference-only — the next backfill run will overwrite them with
    // the orchestrator output. Hand-edit on Shopify Admin if you need to
    // override.
    {
      name: 'careInstructions',
      title: '🛒 Care Instructions (bullets)',
      type: 'array',
      group: 'care',
      description: 'Imperative care steps (cleaning, charging, storage, lube compat). The PDP Care card prefers care-categorized FAQs; this list is the fallback. 🛒 Source: Shopify metafield `xdipx.care_instructions`.',
      of: [{ type: 'string' }],
      validation: Rule => Rule.max(8),
      readOnly: true,
    },
    {
      name: 'specifications',
      title: '🛒 Specifications',
      type: 'array',
      group: 'care',
      description: 'Tech spec bullets — one "Label: Value" pair per item (e.g. "Color: Black", "Material: Nylon straps"). Renders in the Specs grid card. 🛒 Source: Shopify metafield `xdipx.specifications`.',
      of: [{ type: 'string' }],
      validation: Rule => Rule.max(15),
      readOnly: true,
    },
    {
      name: 'boxContents',
      title: '🛒 In the Box',
      type: 'array',
      group: 'care',
      description: 'What ships in the package. Renders in the "In the box" grid card. 🛒 Source: Shopify metafield `xdipx.box_contents`.',
      of: [{ type: 'string' }],
      validation: Rule => Rule.max(12),
      readOnly: true,
    },

    // category — multi-select audience tags. A product can be any combination
    // of for-him / for-her / couples (e.g. ['for-him', 'couples'] = he can use
    // it solo OR with a partner). Empty = unspecified. The legacy single-value
    // 'both' was redundant — it's now expressed as ['for-him', 'for-her'].
    // Used by IVR/chat search filters and the AI agent's product tools.
    {
      name: 'category',
      title: '🛒 Category',
      type: 'array',
      group: 'product',
      description: 'Audience targeting — pick any that apply. Multi-select. 🛒 Source: Shopify metafield `xdipx.category`.',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'For Him',  value: 'for-him' },
          { title: 'For Her',  value: 'for-her' },
          { title: 'Couples',  value: 'couples' },
        ],
        layout: 'list',
      },
      readOnly: true,
    },
    // Deal-pipeline fields (dealStatus, dealDate, originalPrice, wholesaleCost,
    // mapPrice, dealScore, nalpacSku) live solely on Shopify metafields where
    // the deal pipeline reads them. Removed from Sanity schema — no app query
    // projects them. Cleanup script unsets the orphaned values on existing
    // docs.
    {
      name: 'archived',
      title: '✏️ Archived',
      type: 'boolean',
      group: 'product',
      description: 'Set automatically by the archive-discontinued backfill, but writable here for manual override. Archived docs are excluded from search. ✏️ Sanity-only — no Shopify counterpart.',
    },
    // WS2c — additive. Import-time stub visibility gate: a productPage created
    // for a not-yet-active (Shopify DRAFT) product is hidden from sitemap.xml
    // and on-site search until the product actually activates. OPT-OUT
    // semantics are intentional: unset/false = visible, so the entire existing
    // live catalog is unaffected with zero backfill. Set true only at stub
    // creation time for a draft-stage import (app/lib/bulk-import.server.ts);
    // cleared to false automatically the moment the product activates, via
    // whichever path calls `activateShopifyProduct` (app/lib/shopify.server.ts
    // — import publish in app/lib/import-enrich.server.ts, the daily deal
    // rotator, or an admin force-activate), which patches it via
    // `markProductPageLive` (app/lib/sanity.server.ts).
    {
      name: 'hiddenUntilLive',
      title: '🔗 Hidden Until Live',
      type: 'boolean',
      group: 'product',
      description: 'True only while the underlying Shopify product is still a DRAFT (not yet purchasable) — hides this page from sitemap.xml and on-site search. Unset/false = visible (the default). Auto-cleared to false when the product activates; safe to flip manually if a stub is ever stuck hidden after going live. 🔗 Auto-managed by the import pipeline.',
      initialValue: false,
    },

    // ── Emma Discovery (auto-filled by orchestrator on bulk import) ─────────
    // These tags drive Emma's chat / IVR / SMS surfaces — search.server.ts and
    // ivr-search.server.ts query *[_type == "productPage"] with these filters.
    // Vocabulary is managed in the askEmmaVocabulary singleton; orchestrator
    // slugifies on write so URL params (?mood=, ?audience=, ?matters=) match.
    {
      name: 'productTypeDial',
      title: '🛒 Product Type (Dial)',
      type: 'string',
      group: 'emma',
      description: 'Coarse type used by sensation dial + chat narrowing ("any wands?"). Phase 1 expanded vocabulary (PR#51). 🛒 Source: Shopify metafield `xdipx.product_type_dial`.',
      readOnly: true,
      options: {
        list: [
          { title: 'Vibrator',      value: 'vibrator'      },
          { title: 'Dildo',         value: 'dildo'         },
          { title: 'Anal',          value: 'anal'          },
          { title: 'Bondage',       value: 'bondage'       },
          { title: 'Cock ring',     value: 'cock-ring'     },
          { title: 'Stroker',       value: 'stroker'       },
          { title: 'Couples',       value: 'couples'       },
          { title: 'Harness',       value: 'harness'       },
          { title: 'Extender',      value: 'extender'      },
          { title: 'Pump',          value: 'pump'          },
          { title: 'Lube',          value: 'lube'          },
          { title: 'Massage',       value: 'massage'       },
          { title: 'Enhancer',      value: 'enhancer'      },
          { title: 'Wear',          value: 'wear'          },
          { title: 'Condom',        value: 'condom'        },
          { title: 'Wellness',      value: 'wellness'      },
          { title: 'Novelty',       value: 'novelty'       },
          { title: 'Book / Media',  value: 'book-media'    },
          { title: 'Sex machine',   value: 'sex-machine'   },
        ],
      },
    },
    {
      name: 'productSubtypeDial',
      title: '🛒 Product Subtype (Dial)',
      type: 'string',
      group: 'emma',
      description: 'Per-parent subtype scoped to productTypeDial (e.g. wand for vibrator, water-based for lube, restraint for bondage). Populated by the orchestrator; null when type is sex-machine or classification was ambiguous. 🛒 Source: Shopify metafield `custom.product_subtype_dial`.',
      readOnly: true,
    },
    {
      name: 'sensationDialV2',
      title: '🛒 Sensation Dial (v2)',
      type: 'object',
      group: 'emma',
      description: 'Self-describing dial: 5–6 dimensions scored 1–5 with an optional `proposed` flag for AI-introduced labels. 🛒 Source: Shopify metafield `xdipx.sensation_dial_v2`.',
      readOnly: true,
      fields: [
        {
          name: 'items',
          title: 'Items',
          type: 'array',
          of: [
            {
              type: 'object',
              name: 'sensationDialItem',
              fields: [
                { name: 'label',    title: 'Label',    type: 'string', validation: Rule => Rule.required() },
                { name: 'value',    title: 'Value (1–5)', type: 'number', validation: Rule => Rule.required().integer().min(0).max(5) },
                { name: 'proposed', title: 'Proposed (new label, awaiting registry approval)', type: 'boolean', initialValue: false },
              ],
              preview: {
                select: { title: 'label', value: 'value', proposed: 'proposed' },
                prepare: ({ title, value, proposed }) => ({
                  title:    title || 'Untitled dimension',
                  subtitle: `${value ?? 0}/5${proposed ? ' · proposed' : ''}`,
                }),
              },
            },
          ],
        },
      ],
    },
    {
      name: 'moodTags',
      title: '🛒 Mood Tags',
      type: 'array',
      group: 'emma',
      description: 'Vibe — slow-and-intimate, playful, etc. Used by Ask Emma rail + chat. 🛒 Source: Shopify metafield `xdipx.mood_tags`.',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
      readOnly: true,
    },
    {
      name: 'audienceTags',
      title: '🛒 Audience Tags',
      type: 'array',
      group: 'emma',
      readOnly: true,
      description: 'Who it\u2019s for — me, us, gift. Drives the "Who\u2019s it for?" filter.',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    },
    {
      name: 'mattersTags',
      title: '🛒 Matters Tags',
      type: 'array',
      group: 'emma',
      description: 'Constraints that matter — quiet, soft-touch, travel-size, waterproof, etc. 🛒 Source: Shopify metafield `xdipx.matters_tags`.',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
      readOnly: true,
    },
    {
      name: 'mattersTagsNormalized',
      title: '🤖 Matters Tags (filter index)',
      type: 'array',
      group: 'emma',
      description: 'Canonical slug form of every entry in `mattersTags`, computed via `app/lib/tag-normalize.ts` — the same slugifier conversation search queries with. Derived field — DO NOT edit directly. Populated by upsertProductPage and scripts/backfill-matters-tags-normalized.ts.',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
      readOnly: true,
      hidden: true,
    },

    // ── IVR / Voice Discovery ─────────────────────────────────────────────────
    // ivrMood removed — duplicated moodTags. IVR search now reads moodTags directly.
    {
      name: 'ivrExperience',
      title: '✏️ Experience Level',
      type: 'array',
      group: 'ivr',
      readOnly: true,
      description: 'Multi-select — pick every level this product fits. Used when callers say "beginner-friendly" or "something advanced". Empty = no level constraint (matches every level). The legacy "any" value is expressed by leaving the field empty. ✏️ Sanity-only — auto-generated by Emma; will overwrite on next backfill.',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'First-time',   value: 'first-time'  },
          { title: 'Curious',      value: 'curious'     },
          { title: 'Experienced',  value: 'experienced' },
          { title: 'Advanced',     value: 'advanced'    },
        ],
        layout: 'list',
      },
    },
    {
      name: 'ivrUseCase',
      title: '✏️ Use Case Tags',
      type: 'array',
      group: 'ivr',
      readOnly: true,
      description: 'Scenarios — date-night, couples-play, kink-curious, etc. Free-form tags; orchestrator validates against the curated 54-value vocab in `IVR_USE_CASES` (app/lib/claude.server.ts). ✏️ Sanity-only — auto-generated by Emma.',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    },
    {
      name: 'ivrFeatures',
      title: '✏️ Feature Tags',
      type: 'array',
      group: 'ivr',
      readOnly: true,
      description: 'Physical features callers ask about — waterproof, quiet, rechargeable, silicone, etc. Free-form tags; orchestrator validates against the curated 100+ value vocab in `IVR_FEATURES` (app/lib/claude.server.ts). ✏️ Sanity-only — auto-generated by Emma.',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    },
    // ivrVoiceSummary deprecated by `deprecate ivrVoiceSummary across the
    // pipeline` — voice surfaces now compose from ivrExperience + ivrUseCase
    // + ivrFeatures directly. Removed from schema.

    // ── Bundle ───────────────────────────────────────────────────────────────
    {
      name: 'isBundle',
      title: '✏️ This product is a bundle',
      type: 'boolean',
      group: 'bundle',
      description: 'When checked, the PDP renders a multi-product bundle hero instead of a single-product layout. Shopify product still needs to exist for the handle/URL. ✏️ Sanity-only — pure editorial.',
      initialValue: false,
    },
    {
      name: 'bundleComponents',
      title: '✏️ Bundle Components',
      type: 'array',
      group: 'bundle',
      description: 'Products included in this bundle. "Dip In ♥" adds each component as its own cart line. ✏️ Sanity-only — pure editorial.',
      hidden: ({ parent }) => !parent?.isBundle,
      of: [
        {
          type: 'object',
          name: 'bundleComponent',
          title: 'Component',
          fields: [
            {
              name: 'product',
              title: 'Product',
              type: 'reference',
              to: [{ type: 'productPage' }],
              validation: Rule => Rule.required(),
            },
            {
              name: 'quantity',
              title: 'Quantity',
              type: 'number',
              initialValue: 1,
              validation: Rule => Rule.required().integer().min(1).max(10),
            },
          ],
          preview: {
            select: { title: 'product.title', subtitle: 'product.shopifyHandle', qty: 'quantity', imageUrl: 'product.previewImageUrl' },
            prepare: ({ title, subtitle, qty, imageUrl }) => ({
              title: title || subtitle || 'Component',
              subtitle: `Qty ${qty ?? 1}${subtitle ? ` · /${subtitle}` : ''}`,
              media: imageUrl
                ? createElement('img', { src: imageUrl, style: { width: '100%', height: '100%', objectFit: 'cover' } })
                : undefined,
            }),
          },
        },
      ],
    },
    {
      name: 'bundleDiscountPct',
      title: '✏️ Bundle Discount (%)',
      type: 'number',
      group: 'bundle',
      description: 'Percent off the combined MSRP of all components. E.g. 20 = 20% off. Applied in Shopify via an automatic discount tied to the bundle tag. ✏️ Sanity-only — pure editorial.',
      hidden: ({ parent }) => !parent?.isBundle,
      validation: Rule => Rule.min(0).max(90),
      initialValue: 0,
    },
    {
      name: 'bundleCompanionFor',
      title: '✏️ Offer On These Product PDPs',
      type: 'array',
      group: 'bundle',
      description: 'Products whose PDP should show a "Bundle & Save" card pointing at this bundle. Leave empty to only surface the bundle on its own URL / homepage. ✏️ Sanity-only — pure editorial.',
      hidden: ({ parent }) => !parent?.isBundle,
      of: [{ type: 'reference', to: [{ type: 'productPage' }] }],
    },

    // ── FAQs / Q&A (additive — emits FAQPage JSON-LD on the PDP) ──────────────
    // Visible Q&A list rendered in the PDP "FAQs / Q&A" card. Visible answer
    // text MUST match JSON-LD; never hide content here. Sweet spot is 4–8
    // questions per product. Emma generates drafts; humans approve in Studio.
    {
      name: 'productFaqs',
      title: '✏️ Product FAQs',
      type: 'array',
      group: 'faqs',
      readOnly: true,
      description: '4 to 8 questions/answers shown on the PDP and emitted as FAQPage JSON-LD. One-line answers get ignored by LLMs. Aim for 1 to 3 sentences. ✏️ Sanity-only — auto-generated by Emma (orchestrator H1); will overwrite on next backfill.',
      of: [{ type: 'productFaq' }],
      validation: Rule => Rule.max(12),
    },

    // ── Content Blocks ────────────────────────────────────────────────────────
    {
      name: 'contentBlocks',
      title: '✏️ Content Blocks',
      type: 'array',
      group: 'content',
      description: 'Blocks that appear below the product details on the PDP. ✏️ Sanity-only — pure editorial (Emma rails, promo banners, trust bar, etc.).',
      of: [
        { type: 'promoBanner'        },
        { type: 'editorialTiles'     },
        { type: 'categoryGrid'       },
        { type: 'productCarousel'    },
        { type: 'reference', name: 'emmaCuratedRailRef', title: 'Emma Curated Rail',
          to: [{ type: 'emmaCuratedRail' }] },
        { type: 'playTogetherBanner' },
        { type: 'brandLogoWall'      },
        { type: 'testimonials'       },
        { type: 'trustBar'           },
        { type: 'editorBio'          },
        // Additive — editor-curated Notebook guides for this product. Optional;
        // the PDP falls back to same-product-type guides when absent.
        { type: 'relatedGuides'      },
      ],
    },
  ],

  preview: {
    select: { title: 'title', subtitle: 'shopifyHandle', imageUrl: 'previewImageUrl' },
    prepare: ({ title, subtitle, imageUrl }) => ({
      title:    title    || subtitle || 'Untitled product',
      subtitle: subtitle ? `/${subtitle}` : '',
      media: imageUrl
        ? createElement('img', {
            src: imageUrl,
            style: { width: '100%', height: '100%', objectFit: 'cover' },
          })
        : undefined,
    }),
  },

  orderings: [
    { title: 'Title A–Z',   name: 'titleAsc',  by: [{ field: 'title',  direction: 'asc'  }] },
    { title: 'Vendor A–Z',  name: 'vendorAsc', by: [{ field: 'vendor', direction: 'asc'  }] },
  ],
}
